version: "3"
services:
  event-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7007:7007"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_DATABASE=onedotcom
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge
